#if !canImport(ObjectiveC)
import XCTest

extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
        ("testAppendContentsOf", testAppendContentsOf),
        ("testChangeContains", testChangeContains),
        ("testContainsAll", testContainsAll),
        ("testContainsAtLeastOne", testContainsAtLeastOne),
        ("testRemoveAll", testRemoveAll),
        ("testRemoveContentsOf", testRemoveContentsOf),
        ("testToggleContains", testToggleContains),
    ]
}

extension CollectionMerginTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionMerginTests = [
        ("testMergeNewOnly", testMergeNewOnly),
        ("testMergeNewOnlySequence", testMergeNewOnlySequence),
        ("testMergeReplacingDuplicates", testMergeReplacingDuplicates),
        ("testMergeReplacingDuplicatesSequence", testMergeReplacingDuplicatesSequence),
    ]
}

extension CollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionTests = [
        ("testContainsOptional", testContainsOptional),
    ]
}

extension IndexWrappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IndexWrappingTests = [
        ("testElementAfter", testElementAfter),
        ("testNextIndex", testNextIndex),
        ("testNextIndexEmpty", testNextIndexEmpty),
        ("testNextIndexOneItem", testNextIndexOneItem),
        ("testWrappingSubscript", testWrappingSubscript),
    ]
}

extension SetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SetTests = [
        ("testChangeContains", testChangeContains),
        ("testInsertContentsOf", testInsertContentsOf),
        ("testToggleContains", testToggleContains),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayTests.__allTests__ArrayTests),
        testCase(CollectionMerginTests.__allTests__CollectionMerginTests),
        testCase(CollectionTests.__allTests__CollectionTests),
        testCase(IndexWrappingTests.__allTests__IndexWrappingTests),
        testCase(SetTests.__allTests__SetTests),
    ]
}
#endif
