#if !canImport(ObjectiveC)
import XCTest

extension CollectionMerginTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionMerginTests = [
        ("testMergeNewOnly", testMergeNewOnly),
        ("testMergeNewOnlySequence", testMergeNewOnlySequence),
        ("testMergeReplacingDuplicates", testMergeReplacingDuplicates),
        ("testMergeReplacingDuplicatesSequence", testMergeReplacingDuplicatesSequence),
    ]
}

extension SetInsertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SetInsertionTests = [
        ("testInsertContentsOf", testInsertContentsOf),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CollectionMerginTests.__allTests__CollectionMerginTests),
        testCase(SetInsertionTests.__allTests__SetInsertionTests),
    ]
}
#endif
