#if !canImport(ObjectiveC)
import XCTest

extension CollectionExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CollectionExtensionsTests = [
        ("testMergeNewOnly", testMergeNewOnly),
        ("testMergeNewOnlySequence", testMergeNewOnlySequence),
        ("testMergeReplacingDuplicates", testMergeReplacingDuplicates),
        ("testMergeReplacingDuplicatesSequence", testMergeReplacingDuplicatesSequence),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CollectionExtensionsTests.__allTests__CollectionExtensionsTests),
    ]
}
#endif
