name: Tests

on: [push, pull_request]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["5.0", "5.1"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build (Release)
      run: swift build -v -c release
    - name: Build (Debug)
      run: swift build -v -c debug
    - name: Test (Release)
      run: swift test -v -c release -Xswiftc -enable-testing
    - name: Test (Debug)
      run: swift test -v -c debug
    - name: Slack Notification
      uses: elegantchaos/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'Linux Tests (Swift ${{ matrix.swift }})'
        mention_if: 'failure'
        url: ${{ secrets.SLACK_WEBHOOK }}

  macos:
    name: Mac
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build (masOS, Release)
      run: swift build -v -c release
    - name: Build (macOS, Debug)
      run: swift build -v -c debug
    - name: Test (macOS, Release)
      run: swift test -v -c release -Xswiftc -enable-testing
    - name: Test (macOS, Debug)
      run: swift test -v -c debug
    - name: Test (iOS, Release)
      run: xcodebuild clean test -workspace . -scheme CollectionExtensions -destination "name=iPad Pro (11-inch)" -configuration Release ENABLE_TESTABILITY=YES
    - name: Test (iOS, Debug)
      run: xcodebuild clean test -workspace . -scheme CollectionExtensions -destination "name=iPad Pro (11-inch)" -configuration Debug
    - name: Slack Notification
      uses: elegantchaos/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: 'macOS/iOS Tests (${{ matrix.config }})'
          mention_if: 'failure'
          url: ${{ secrets.SLACK_WEBHOOK }}
